<?php
$__VERSION__ = "___VERSION_STRING___"
?>
<!DOCTYPE html>
<html lang = "en">

<head>
    <meta charset = "UTF-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>

    <title>Assessment Portal</title>
    <!-- script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script> -->



    <!-- Additional CSS styling -->
    <!-- <link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet"/> -->

    <!-- Latest compiled and minified CSS -->
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"/> -->

    <!-- Latest compiled and minified JavaScript -->
    <!-- <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script> -->




</head>

<body>
<div id = "app"></div>
<div id = "popups"></div>
<div style="display:inline-block;position:fixed;top:100%;left:100%;transform:translate(-100%,-100%);padding:10px;color:black;font-weight:bold"><?php echo $__VERSION__; ?></div>
<script>
var $__VERSION__ = "<?php echo $__VERSION__; ?>"
</script>
<script src = "/resources/index.js"></script>
</body>

</html>
